name: Playwright Minimal Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: oven-sh/setup-bun@v2
      
      - name: Install dependencies
        run: bun install
      
      - name: Install Playwright
        run: bunx playwright install --with-deps chromium
      
      - name: Start web app
        run: |
          cd apps/client
          bun run web &
          sleep 30
        
      - name: Run Playwright test
        run: bunx playwright test
      
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

